name: Build

on:
  push:
    branches: [ "master", "release" ]
  pull_request:
    branches: [ "master", "release" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v2

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
